### ISSUE TITLE
what about using iter dataset

### ISSUE THREAD

**Issue by DuinoDu** [TheGreatCold/rank_dataset#1]
rankdataset is proposed to solve memory problem when loading all label at once. what about loading label during training using iter dataset?

**Comment by yqyao** [comment]
Dataset must be reinitialized after one epoch for generating random index @DuinoDu

**Comment by zjykzj** [comment]
> rankdataset is proposed to solve memory problem when loading all label at once. what about loading label during training using iter dataset?

see #2
